# Generated by Django 2.2.16 on 2023-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230311_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='IngridientReciepe',
            new_name='IngredientReciepe',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name_ingridient',
            new_name='name_ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientreciepe',
            old_name='ingridients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
