# Generated by Django 2.2.16 on 2023-03-09 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ingridient', models.CharField(help_text='Укажите название ингридиента', max_length=50)),
                ('amount', models.FloatField(help_text='Введите количество')),
                ('unit', models.CharField(help_text='Введите единицу измерения', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(help_text='Введи тег', max_length=20, unique=True)),
                ('color', models.ImageField(upload_to='static/images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=30, verbose_name='Название')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('description', models.CharField(help_text='Придумайте описание', max_length=100)),
                ('time_cook', models.DateTimeField(help_text='Выберите время приготовления')),
                ('author', models.ForeignKey(help_text='Введите имя автора рецепта', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingridients', models.ManyToManyField(help_text='Выберите ингридиенты', to='recipes.Ingridient')),
                ('tags', models.ManyToManyField(help_text='Выберите теги', to='recipes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='IngridientReciepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Введите количество продукта')),
                ('ingridients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingridient')),
                ('reciepes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
    ]
