# Generated by Django 2.2.16 on 2023-03-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230311_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cookinng_time',
            new_name='cooking_time',
        ),
    ]
