# Generated by Django 2.2.16 on 2023-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230311_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='amount',
            field=models.FloatField(help_text='Введите количество', null=True),
        ),
    ]
