# Generated by Django 2.2.16 on 2023-03-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230311_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Выберите время приготовления'),
        ),
    ]
