# Generated by Django 2.2.16 on 2023-03-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230312_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name_ingredient',
            new_name='name',
        ),
    ]
