# Generated by Django 2.2.16 on 2023-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230320_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите уникальный логин', max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
