# Generated by Django 2.2.16 on 2023-03-20 18:58

from django.db import migrations, models
import django.db.models.expressions
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230320_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите вашу электронную почту', max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введи вашем Имя', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите вашу фамилию', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите уникальный логин', max_length=150, unique=True, validators=[users.validators.validate_username_me, users.validators.validate_username], verbose_name='Логин'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='no_subscribe'),
        ),
    ]
