# Generated by Django 2.2.16 on 2023-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230315_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientreciepe',
            name='amount',
            field=models.PositiveIntegerField(help_text='Введите количество продукта', verbose_name='Количество'),
        ),
    ]
