# Generated by Django 2.2.16 on 2023-03-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230315_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientreciepe',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
