# Generated by Django 2.2.16 on 2023-03-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230315_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientreciepe',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.Recipe', verbose_name='Рецепт'),
        ),
    ]
